### ISSUE TITLE
[Feature Request] Battery Level Disable Option

### ISSUE THREAD

**Issue by kenderson** [blaineam/homebridge-august-smart-locks#44]
Awesome work on the platform! Is there an easy way to disable the battery levels? Perhaps a config option?

**Comment by bvelazquez1** [comment]
I would like this feature as well. My august lock needed the batteries replaced and after doing so, the battery level warning is still showing up.

**Comment by xcsdm** [comment]
I don't know how to create the option.  I haven't gotten that far into Homebridge schemas and how that might work.
However, I did remove the Battery status completely from the latest 5.1 version of this plugin.

I did it by CLI and editing the platform.js for this npm package and commenting any line or block of code that referenced batt, Battery, etc.  I don't know enough about git or npm to redistribute it.
