### ISSUE TITLE
Door sensor only?

### ISSUE THREAD

**Issue by ac4lt** [blaineam/homebridge-august-smart-locks#47]
Is there a way to configure the plugin to only bring in the door contact sensor and ignore the locks?

If not, this would be a great feature. I'm happy with the native August homekit support except for not exposing the door sensors. If I could just get the sensor accessories added via the plugin it would be fantastic.

**Comment by tmenguy** [comment]
same here now :)

**Comment by akseez** [comment]
I am also interested in this feature.

**Comment by MikeDProducer** [comment]
I would love this, too.

**Comment by Sujovian** [comment]
Same here. With Native HK support already, Doorsense is the primary interest I have in this plugin.

**Comment by JaviSoto** [comment]
I would also like the opposite :) the native HomeKit support is awful, so I'm using this plugin which works great, but  I'm not using the contact sensors.

**Comment by fratinize** [comment]
This would be great

**Comment by deepontech** [comment]
I would appreciate this feature too. Would like to have the sensors exposed.
