### ISSUE TITLE
Have to keep get new 2fa code

### ISSUE THREAD

**Issue by hubz87** [blaineam/homebridge-august-smart-locks#63]
Almost daily I have to get a new 2fa code? I get an error in the logs that says get failed 401

**Comment by jvs2010** [comment]
I am having the same issue. I get the following error:

August Smart Locks Bridge AugustLocks [August] Could not communicate with August API: GET failed with: 401

This error then repeats in the log every six seconds.

If I delete the 2FA code from the configuration and stop/restart the bridge on HOOBS, I get a new 2FA code from August. I then have to add this to the configuration and re-start the bridge again. The locks then work again for about a day.  I looked to see if this 401 error was happening at the same time each day (e.g. 24 hours after I input the 2FA code), but it's not. It seems to happen around every 20 hours or so.

I also continue to get a "write handler for the characteristic 'Lock Target State'" error.  (See separate issue filled previously.) I am not sure if this is related or not.

**Comment by brianjw** [comment]
Also having the same issue. This issue just started happening over the last few days. Previously, I had to get a new 2FA code once every couple of months, but it has now become a daily task.

Receiving the exact same error as the others:
`[AugustLocks] [August] Could not communicate with August API: GET failed with: 401`

Screenshot of my full configuration for reference:
![hb-aug](https://user-images.githubusercontent.com/817666/162300611-f5361e06-1df6-4757-8901-7f9a7e153e1c.png)
