### ISSUE TITLE
Upgrade to event based api

### ISSUE THREAD

**Issue by rubenstolk** [blaineam/homebridge-august-smart-locks#66]
I was looking at this repo: https://github.com/hufftheweevil/august-api which has an event based architecture. Do you think we can easily upgrade this module to consume that so that things like door and lock state are real time instead of polling delays?

**Comment by mojodean** [comment]
It's a great idea. It seems that both of the Homebridge modules for August Locks (this one and https://github.com/nnance/homebridge-august-locks as well) have been more-or-less abandoned, so I wonder if it's worth setting up a new project?

**Comment by donavanbecker** [comment]
@rubenstolk & @mojodean , I am going to try it.

Watch: [homebridge-august](https://github.com/donavanbecker/homebridge-august) for updates.

**Comment by mojodean** [comment]
@donavanbecker amazing! I *think* the https://github.com/nnance/homebridge-august-locks project has more updates/commits from other folks, so might be able to build off of that easier than this one, but not sure.

**Comment by donavanbecker** [comment]
@mojodean, I am pretty far with my plugin so far. Will need to enable the events based update and make push changes better. But if you wanna try the latest beta you can.

**Comment by donavanbecker** [comment]
@mojodean  & @rubenstolk, Latest beta has Events!!!

homebridge-august@0.1.0-beta.16

**Comment by mojodean** [comment]
Awesome! Just installed. Are the battery percentages legit/what August is reporting?

**Comment by donavanbecker** [comment]
v1.0.4 resolves the issue.
